### ISSUE TITLE
Change inspect icon in Icon Preview

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/svgps.app#220]
![image](https://user-images.githubusercontent.com/7966133/195658978-a30714f6-196a-4ad5-a95e-6f7c1e916652.png)

New Icon
https://user-images.githubusercontent.com/7966133/195658999-03bee2ad-1032-4b8b-b42c-12c6d7248ee7.svg

**Comment by alpercun** [comment]
I can deal with this issue!
