### ISSUE TITLE
Fix `copy to clipboard` button style when the svg name is too long

### ISSUE THREAD

**Issue by alpercun** [aykutkardas/svgps.app#227]
![image](https://user-images.githubusercontent.com/32914083/195985306-9efe6df7-0031-48f6-87f0-70292e3fb5f8.png)

**Comment by aykutkardas** [comment]
- [ ] The name should always be a single line.  It can be abbreviated with `...`. 
- [ ] The copy icon size should always remain the same.

**Comment by LuizHAP** [comment]
Please, assign to me!

**Comment by aykutkardas** [comment]
> Please, assign to me!

Do you have any progress on this issue? @LuizHAP

**Comment by hasantezcan** [comment]
I can fix that issue, if no update from LuizHAP

**Comment by hasantezcan** [comment]
> I can fix that issue, if no update from LuizHAP @aykutkardas

I can fix that issue, if no update from LuizHAP @aykutkardas

**Comment by hasantezcan** [comment]
> > Please, assign to me!
> 
> Do you have any progress on this issue? @LuizHAP

I can fix that issue, if no update from LuizHAP @aykutkardas
