### ISSUE TITLE
Add remove text icon when search bar is not empty

### ISSUE THREAD

**Issue by alpercun** [aykutkardas/svgps.app#228]
![image](https://user-images.githubusercontent.com/32914083/195985492-eca1aded-d5ec-4048-abb1-229523c5553e.png)

**Comment by batin** [comment]
I can handle this one.

**Comment by batin** [comment]
Do you have any specific icon that you want to use for it? @aykutkardas

**Comment by aykutkardas** [comment]
You can use the `x-circle` icon in Heroicons Outline.

https://svgps.app/store/heroicons/outline/
